# Generated by Django 6.0.4 on 2026-05-04 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head_title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-building', max_length=50)),
                ('color', models.CharField(default='#2D6A4F', max_length=20)),
                ('bg_color', models.CharField(default='#D8F3DC', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Restructuring', 'Restructuring'), ('Disbanded', 'Disbanded')], default='Active', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('slack_channel', models.CharField(blank=True, max_length=100)),
                ('teams_channel', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default='#2D6A4F', max_length=20)),
                ('standup_time', models.CharField(blank=True, max_length=50)),
                ('jira_project', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='teams.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('Infrastructure Support', 'Infrastructure Support'), ('Bug Resolution', 'Bug Resolution'), ('API Integration', 'API Integration'), ('Data Feed', 'Data Feed'), ('Security Compliance', 'Security Compliance'), ('Deployment', 'Deployment'), ('General', 'General')], default='General', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_deps', to='teams.team')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_deps', to='teams.team')),
            ],
            options={
                'unique_together': {('from_team', 'to_team')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Team Lead', 'Team Lead'), ('Senior Engineer', 'Senior Engineer'), ('Engineer', 'Engineer'), ('Junior Engineer', 'Junior Engineer'), ('DevOps', 'DevOps'), ('QA Engineer', 'QA Engineer'), ('Data Scientist', 'Data Scientist'), ('Architect', 'Architect')], default='Engineer', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
    ]
